server:
  port: 8090
spring:
  application:
    name: cloud-feign-order-service
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 2000
          cloud-payment-service:
            readTimeout: 5000