server:
  port: 8090
spring:
  application:
    name: cloud-feign-order-service
  cloud:
    openfeign:
      client:
        config:
          default:
            readTimeout: 20000
            connect-timeout: 20000
          cloud-payment-service:
            connect-timeout: 20000
            readTimeout: 20000
#      circuitbreaker:
#        enabled: true
#        group:
#          enabled: true
resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50
#        sliding-window-type: count_based
#        sliding-window-size: 6
#        minimum-number-of-calls: 6
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state:
#          seconds: 5
#        permitted-number-of-calls-in-half-open-state: 2
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 20
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration:
          seconds: 2
    instances:
      cloud-payment-service:
        base-config: default
